config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from dvishparish.api import api
urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "api/", TemplateView.as_view(template_name="pages/api.html"), name="api_docs"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("dvishparish.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("dashboard/", include("dvishparish.manager_roles.urls")),
                  # Your stuff: custom urls includes go here
    path('api-auth/', include('rest_framework.urls')),


    path('api/', include(api.router.urls)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

dvishparish/manager_roles/urls.py
from django.urls import path

from dvishparish.manager_roles import views

app_name = "manager_roles"


urlpatterns = [
    path(r"KPIs/", views.ManagerKPIsView.as_view(), name="self_kpis"),
    path(r"top5/", views.Top5ManagersView.as_view(), name="top_managers"),
    path(r"kpis_list/", views.ListKPIView.as_view(), name="list_kips"),
]

dvishparish/users/urls.py
from django.urls import path

from dvishparish.users import views
app_name = "users"
urlpatterns = [
    path("~redirect/", view=views.user_redirect_view, name="redirect"),
    path("~update/", view=views.user_update_view, name="update"),
    path("", view=views.UserDetailView.as_view(), name="detail"),
]

dvishparish/manager_roles/models.py
from django.db import models
from dvishparish.users.models import User
from dvishparish.plans.models import KPI
from django.core.validators import MinValueValidator


class ResultDaily(models.Model):
    user = models.ForeignKey(User, related_name="results_daily", on_delete=models.CASCADE)
    date_add = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} - {self.date_add}"


class ResultItem(models.Model):
    result_daily = models.ForeignKey(ResultDaily, related_name="results_items",
                                     on_delete=models.CASCADE)
    KPI = models.ForeignKey(KPI, related_name="results_items", on_delete=models.CASCADE)
    KPI_result_amount = models.DecimalField(
        default=0,
        max_digits=8,
        decimal_places=2,
        validators=[
            MinValueValidator(1)
        ])

    def __str__(self):
        return f"{self.KPI}, {self.KPI_result_amount}"

dvishparish/plans/models.py
from django.db import models
from dvishparish.users.models import User, BankOffice
from django.contrib.auth import get_user_model
from django.utils import timezone

from django.core.validators import MaxValueValidator, MinValueValidator


class Formula(models.Model):
    name = models.CharField(max_length=150)
    percentage_on_salary = models.DecimalField(
        default=20,
        max_digits=8,
        decimal_places=2,
        validators=[
            MinValueValidator(1)
        ])

    percentage_of_the_plan = models.DecimalField(
        default=100,
        max_digits=8,
        decimal_places=2,
        validators=[
            MinValueValidator(100)
        ])
    is_bankoffice = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} - Відсоток премії {self.percentage_on_salary}%. Виконати план на {self.percentage_of_the_plan}%"


class KPI(models.Model):
    is_general_plan = models.BooleanField(default=False)
    indicator_name = models.CharField(max_length=150)
    formula = models.ForeignKey(Formula, related_name='KPI_f', on_delete=models.CASCADE, null=True, blank=True)
    formula_bankoffice = models.ForeignKey(Formula, related_name='KPI_fb', on_delete=models.CASCADE, null=True, blank=True)

    target_amount = models.DecimalField(
        default=0,
        max_digits=8,
        decimal_places=2,
        validators=[
            MinValueValidator(0)
        ])

    date_from = models.DateTimeField(default=timezone.now())
    date_to = models.DateTimeField()
    
    # class Meta:
    #     unique_together = ("formula", "formula_bankoffice")

    def __str__(self):
        return f"{self.indicator_name} | {self.date_from} - {self.date_to} {self.target_amount}"


class GeneralPlan(models.Model):
    date_from = models.DateTimeField(default=timezone.now())
    date_to = models.DateTimeField()

    def __str__(self):
        return f"{self.date_from} - {self.date_to}"


class KPIitem(models.Model):
    KPI = models.ForeignKey(KPI, related_name='kpi_items', on_delete=models.CASCADE)
    general_plan = models.ForeignKey(GeneralPlan, related_name="kpi_items", on_delete=models.CASCADE)

class BankOfficeKPI(models.Model):
    bankoffice = models.ForeignKey(BankOffice, related_name='bankoffice_kpis', on_delete=models.CASCADE)
    KPI = models.ForeignKey(KPI, related_name='bankoffice_kpis' , on_delete=models.CASCADE, blank=True, null=True)
    amount =  models.DecimalField(
        default=0,
        max_digits=8,
        decimal_places=2,
        validators=[
            MinValueValidator(0)
        ])

    def __str__(self):
        return f"{self.KPI.__str__()} | {self.bankoffice.__str__()} - {self.amount}"


class ManagerKPI(models.Model):
    user = models.ForeignKey(User,  related_name='manager_kpis', on_delete=models.CASCADE)
    KPI = models.ForeignKey(KPI, related_name='manager_kpis' , on_delete=models.CASCADE, blank=True, null=True)
    amount =  models.DecimalField(
        default=0,
        max_digits=8,
        decimal_places=2,
        validators=[
            MinValueValidator(0)
        ])

    def __str__(self):
        return f"{self.KPI.__str__()} | {self.user.__str__()} - {self.amount}"

dvishparish/users/models.py
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.utils import timezone


class BankOffice(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    city = models.CharField( blank=True, max_length=255)
    address = models.CharField( blank=True, max_length=255)

    def __str__(self):
        return f"№{self.id} {self.city} {self.address}"


class User(AbstractUser):
    """Default user for dvishparish."""

    bankoffice =  models.ForeignKey(BankOffice, related_name='users', on_delete=models.CASCADE, null=True, blank=True)
    salary = models.DecimalField( default=0, max_digits=8, decimal_places=2, null=True)
    integration_id = models.CharField(max_length=255, null=True, blank=True)

    def get_groups_display(self):
        return " ".join(self.groups.all().values_list('name', flat=True))

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail")


class AbstractPremia(models.Model):
    amount = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    date = models.DateTimeField(default=timezone.now())
    status = models.CharField(choices=(
        ("approved", "approved"),
        ("process", 'process')),
        max_length=20, default="process")

    def __str__(self):
        return f"{self.user.__str__()} - {self.amount}UAH {self.date.strftime('%m/%d/%Y')}"

    class Meta:
        abstract = True
        

class Premium(AbstractPremia):
    user = models.ForeignKey(User, related_name='premiums', on_delete=models.CASCADE)


class Bonus(AbstractPremia):
    user = models.ForeignKey(User, related_name='Bonus', on_delete=models.CASCADE)

dvishparish/plans/forms.py
from django import forms
from .models import Formula, KPI, ManagerKPI
#from .utils import get_bankoffice_amounts
from django.core.exceptions import ValidationError


class KPIForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['formula'].queryset = Formula.objects.filter(is_bankoffice=False)
        self.fields['formula_bankoffice'].queryset = Formula.objects.filter(is_bankoffice=True)

    class Meta:
        model = KPI
        fields = "__all__"

dvishparish/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django import forms

User = get_user_model()

from rolepermissions.roles import assign_role

class UserChangeForm(admin_forms.UserChangeForm):
    
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

dvishparish/manager_roles/views.py
from django.views.generic import TemplateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from rolepermissions.mixins import HasRoleMixin
from dvishparish.utils.manager import get_top_5_menegers_with_general_plan
from dvishparish.plans.models import ManagerKPI, KPI
from .models import ResultDaily


class ManagerKPIsView(HasRoleMixin, LoginRequiredMixin, ListView):
    """Render Dashboard page."""
    template_name = "roles/manager/KPIs.html"
    allowed_roles = 'manager'
    model = ManagerKPI
    paginate_by = 30

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class ResultDailyView(HasRoleMixin, LoginRequiredMixin, ListView):
    template_name = "roles/manager/result.html"
    model = ResultDaily
    paginate_by = 30
    allowed_roles = 'manager'


class Top5ManagersView(HasRoleMixin, LoginRequiredMixin, TemplateView):
    """Render Dashboard page."""
    template_name = "roles/manager/top5_managers.html"
    allowed_roles = 'manager'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tops'] = get_top_5_menegers_with_general_plan(self.request.user)
        print(context)
        return context


class ListKPIView(HasRoleMixin, LoginRequiredMixin, ListView):
    model = ManagerKPI
    allowed_roles = 'manager'
    template_name = "roles/manager/kpis_list.html"

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

dvishparish/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User

    def get_object(self):
        return self.request.user


user_detail_view = UserDetailView.as_view()
class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail")
    
    def get_object(self):
        return User.objects.get(username = self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail")


user_redirect_view = UserRedirectView.as_view()

dvishparish/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}dvishparish{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Behold My Awesome Project!">
    <meta name="author" content="Daniel Roy Greenfeld">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
     <link href="{% static "css/fontawesome.min.css"  %}" rel="stylesheet" type="text/css">

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/material-kit.min.css' %}">    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static "images/logo.png" %}" style="
    height: 60px;
    padding: 0 10px;
    margin-top: -20px;
"><span>
СКАРБничка
        </span>
        </a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link"  {% if request.path == "/" %}style="background-color: #4dd0e1"{% endif %}  href="{% url 'home' %}">Головна <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link"  {% if request.path == "/about/" %}style="background-color: #4dd0e1"{% endif %} href="{% url 'about' %}">Про нас</a>
            </li>
            <li class="nav-item">
              <a class="nav-link"  {% if request.path == "/api/" %}style="background-color: #4dd0e1"{% endif %} href="{% url 'api_docs' %}">API</a>
            </li>

            {% if request.user.is_authenticated %}
                {% if user.groups.first.name == "manager" %}

              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" {% if request.path == "/users/" %}style="background-color: #4dd0e1"{% endif %} href="{{ user.get_absolute_url }}">{% trans "Мій профіль" %}</a>
              </li>              <li class="nav-item">
                <a class="nav-link"  {% if request.path == "/dashboard/KPIs/" %}style="background-color: #4dd0e1"{% endif %} href="{% url 'manager_roles:self_kpis' %}">{% trans "Ваші квести" %}</a>
              </li>
                <li class="nav-item">
                <a class="nav-link"  {% if request.path == "/dashboard/top5/" %}style="background-color: #4dd0e1"{% endif %} href="{% url 'manager_roles:top_managers' %}">{% trans "Рейтинг" %}</a>
              </li>
                <li class="nav-item">
                <a class="nav-link" {% if request.path == "/dashboard/kpis_list/" %}style="background-color: #4dd0e1"{% endif %}  href="{% url 'manager_roles:list_kips' %}">{% trans "Квести і нагороди" %}</a>
              </li>
                    {% endif %}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Вийти" %}</a>
              </li>

            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Вхід" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      <link rel="stylesheet" type="text/css" href="{% static 'js/material-kit.min.js' %}">    
      <script src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}
  </body>
</html>
 